# Generated by Django 3.2 on 2021-04-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210422_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.metric'),
        ),
    ]
